---
website_url: terra.pimbi.icu
datadog_api_key: "{{ encrypted.datadog_api_key }}"
datadog_site: datadoghq.eu
datadog_checks:
  http_check:
    init_config:

    instances:
      - name: Hexlet DevOps Study website
        url: https://{{ website_url }}/
        method: GET
